---
title: "Final_chart"
author: "Jakeschonberger"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(data.table)
library(janitor)
library(readr)
library(readxl)
library(datapasta)
library(tidyr)
library(gganimate)
library(gt)
library(tidyverse)


```

```{r data, include=FALSE, warning = FALSE, message = FALSE}

g20 <- read_csv("raw_data/g20_financial_indicators.csv") %>% clean_names()
life_exp <- read_csv("raw_data/life-expectancy.csv") %>% clean_names()

```

```{r charts, include=FALSE, warning = FALSE, message = FALSE}

## Cleaning g20 data
financial_inclucsion <- list("Deposit accounts per 1,000 adults",	
                             "Retail cashless transactions per 1,000 adults",
                             "Outstanding loans per 1,000 adults")
inclusion_df <- g20 %>% 
  filter(series_name %in% financial_inclucsion) %>% 
  setnames(old=c("x2011_yr2011","x2012_yr2012", "x2013_yr2013","x2014_yr2014", "x2015_yr2015", 
                 "x2016_yr2016", "x2017_yr2017"), new=c("2011", "2012", "2013", "2014", "2015", "2016", "2017"), skip_absent=TRUE) %>% 
  gather(Year, Total, 5:11) %>% 
  transform(Total= as.numeric(Total)) %>% transform(Year= as.numeric(Year))

# Build Cashless transactions by year chart.
cashless_by_year <- inclusion_df %>% filter(series_name =="Retail cashless transactions per 1,000 adults") %>% 
  filter(Year > 2011) %>% 
  filter(Year < 2016) %>% 
  ggplot(aes(x=Year, y=Total, color = country_code)) + 
  geom_line(show.legend = FALSE) +
          scale_y_log10() +
  theme_minimal() +
  geom_point(aes(group = seq_along(Year), show.legend = FALSE)) +
  transition_reveal(Year) + 
  labs(title = "Cashless Transactions by Year", y = "Cashless Transactions / 1000 adults")

g20countries <- c(c("China",
"India",
"Euro Area",
"United States",
"Indonesia",
"Brazil",
"Russia",
"Japan",
"Mexico",
"Germany",
"Turkey",
"France",
"United Kingdom",
"Italy",
"South Africa",
"South Korea",
"Spain",
"Argentina",
"Canada",
"Saudi Arabia",
"Australia",
"Netherlands",
"Switzerland",
"Singapore"))
# Clean life_exp data / select data to match g20 data.
inclusion_df <- inclusion_df %>% clean_names()
life_exp_join <- life_exp %>% filter(entity %in% g20countries) %>% filter(year %in% c(2011,2012,2013,2014,2015,2016))
inclusion_life<- full_join(life_exp_join, inclusion_df, by = c("year" = "year", "entity"  = "country_name"))

life_cashless_by_year <- inclusion_life %>% filter(series_name =="Retail cashless transactions per 1,000 adults") %>% 
  filter(year > 2011) %>% 
  filter(year < 2016) %>% 
  ggplot(aes(x=total, y=life_expectancy_years, color = country_code)) + 
  geom_line(show.legend = FALSE) +
  theme_minimal() +
  geom_point(aes(group = seq_along(year), show.legend = FALSE))  +
  transition_reveal(year) + 
  labs(title = "Life Expectency by mobile growth", y = "Life expectency", x = "Number of cashless transtions per 1000 adults")
```

## Cashless transactions by year, by Country.
`r cashless_by_year`

## Relationship between Cashless transations & Life Expectancy.
`r life_cashless_by_year`
